# Generated by Django 5.1 on 2024-10-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TickerBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=200, unique=True)),
                ('ticker_symbol', models.CharField(max_length=20, unique=True)),
                ('ticker_sector', models.CharField(choices=[('Automobile', 'Automobile'), ('Banking', 'Banking'), ('Capital Goods', 'Capital Goods'), ('Cement', 'Cement'), ('Chemicals', 'Chemicals'), ('Finance', 'Finance'), ('FMCG', 'FMCG'), ('Index', 'Index'), ('Infrastructure', 'Infrastructure'), ('Media', 'Media'), ('Metals', 'Metals'), ('Oil and Gas', 'Oil and Gas'), ('Pharma', 'Pharma'), ('Power', 'Power'), ('Realty', 'Realty'), ('Technology', 'Technology'), ('Telecom', 'Telecom'), ('Textile', 'Textile'), ('Others', 'Others')], default='Others', max_length=50)),
                ('ticker_sub_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker_market_cap', models.CharField(choices=[('Large Cap', 'Large Cap'), ('Mid Cap', 'Mid Cap'), ('Small Cap', 'Small Cap')], default='Large Cap', max_length=20)),
            ],
        ),
    ]
