# Generated by Django 5.1.2 on 2024-10-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scannerpro', '0002_stockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
